name: Post leetcode job information to discord channel

on:
  workflow_dispatch:
  schedule:
      - cron:  '0 0 1,15,29 * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - run: go run main.go
        env:
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          DISCORD_CHANNEL_ID: ${{secrets.DISCORD_CHANNEL_ID}}
          API_KEY: ${{secrets.API_KEY}}
      - run: git add .
      - run: git commit -m "update job informations"
      - run: git push